### ISSUE TITLE
Prevent stopping at walls

### ISSUE THREAD

**Issue by Ishan1742** [arnav-t/Shooting-Game#22]
Can make the player move in the general direction of walls, instead of stopping. When a player hits a wall.

**Comment by mathrulestheworld** [comment]
yes  the  only stop  happens  when  he  hits  perpendicular to the wall.and  we  have  to  deal  with  edges also.

**Comment by mathrulestheworld** [comment]
sent a PR for this one

**Comment by arnav-t** [comment]
Fixed in #73
