### ISSUE TITLE
Reload bar working even after player is dead

### ISSUE THREAD

**Issue by Ishan1742** [arnav-t/Shooting-Game#23]
![screenshot from 2018-12-02 13-01-24](https://user-images.githubusercontent.com/28984539/49337054-0310d580-f633-11e8-8afd-975b714da494.png)

Reload bar working on left-click even when player is dead. Prevent it from reloading.

**Comment by mathrulestheworld** [comment]
yes i have  seen it. if  we  tap our mouse  it  kind a  reloads.

**Comment by mathrulestheworld** [comment]
i have fixed this

**Comment by arnav-t** [comment]
Fixed in #35
