### ISSUE TITLE
add score of player

### ISSUE THREAD

**Issue by mathrulestheworld** [arnav-t/Shooting-Game#33]

**Comment by arnav-t** [comment]
The score can be displayed using OpenCV's `putText()` function.
https://docs.opencv.org/3.0-beta/modules/imgproc/doc/drawing_functions.html#puttext

**Comment by mathrulestheworld** [comment]
![screenshot from 2018-12-04 15-32-50](https://user-images.githubusercontent.com/33874664/49434345-02667380-f7da-11e8-8fe7-7b25d9e782d3.png)

**Comment by arnav-t** [comment]
Added in #48
